### ISSUE TITLE
Blockhash

### ISSUE THREAD

**Issue by ClashLuke** [HistoriaOffical/historia#15]
I see you've picked X16R2 as your hashing algorithm. Could you please elaborate why you chose this particular algorithm? Was it simply convenient, as you forked raven?\
As I am interested in seeing this project grow, I would be interested in potentially forking away to something as fast and insecure as Blake3 or Kanga12. If you're more after the ASIC resistance, we could also work on integrating Bidash or RandomX.

I'm sorry if this is the wrong way to reach out. I couldn't find a proposal site, like those for AEON and PIVX.

**Comment by marshalljp** [comment]
We didn't actually fork Raven. We forked the Dash code base. Originally we used X16R, and mostly it was just a national progression to move from X16R to X16Rv2. For future questions you can email info@historia.network or you can get on our Discord. Proposal site is coming soon.

**Comment by ClashLuke** [comment]
Thanks for getting in touch and explaining your story a bit to me.\
I'm sorry I didn't go into detail above. The main thing I wanted to ask was whether you'd be interested in changing to a different algorithm as using another coins algorithm isn't a good idea as research shows. A discussion can be found [here](https://blog.coinbase.com/how-coinbase-views-proof-of-work-security-f4ba1a139da0) with the replies being [here](https://www.monerooutreach.org/stories/response-to-coinbase.html) and [here](https://github.com/Karbovanets/papers/blob/master/POWS4.md).

**Comment by marshalljp** [comment]
Thanks for the info. We may move to a different hashing algorithm in the future, but currently there are many more important things we need to get done first.
